services:
  - type: web
    name: whatsapp-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node pair.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        generateValue: false
